/**
 * Centralized Permission Matrix and Default Role Templates
 */

export const PERMISSION_GROUPS = [
  {
    groupId: 'ledger',
    groupName: 'Sale Ledger & Voucher Entry',
    description: 'Create, view, update, and manage 2D lottery bet entries and vouchers',
    permissions: [
      { key: 'ledger.view', name: 'View Sale Ledger', description: 'Access the 2D betting entry screen and 00–99 totals aggregate table' },
      { key: 'ledger.create', name: 'Create / Save Voucher', description: 'Submit and record new bet entry numbers for an agent' },
      { key: 'ledger.update', name: 'Update / Edit Voucher', description: 'Modify existing voucher numbers, amounts, or agent assignment' },
      { key: 'ledger.delete', name: 'Delete Voucher', description: 'Permanently remove a voucher slip and recalculate session totals' },
      { key: 'ledger.quick_entry', name: 'Quick Entry Tool', description: 'Use modal dialog to batch-enter number series with shared amounts' },
      { key: 'ledger.import', name: 'Import Entries (JSON / CSV)', description: 'Upload files or paste JSON/CSV data to bulk-populate voucher tokens' },
      { key: 'ledger.manage_tokens', name: 'Inline Token Edit & Delete', description: 'Edit individual number tokens inline or delete selected cell tokens' },
      { key: 'ledger.set_lucky', name: 'Set Lucky Winning Number', description: 'Set or modify the official winning number for the session' },
      { key: 'ledger.set_limit', name: 'Set Session Bet Limit', description: 'Configure max allowable betting limit per number for the active session' },
      { key: 'ledger.check_agent', name: 'Check Agent Number Sales', description: 'Inspect breakdown of sales by agent on a specific 2-digit number' },
      { key: 'ledger.sync_rtdb', name: 'Recalculate & Sync Ledger', description: 'Force recalculation and sync session totals with Realtime Database' },
      { key: 'ledger.export_grid', name: 'Export 00–99 Grid CSV', description: 'Download 00–99 totals table as a CSV file' },
      { key: 'ledger.copy_exceed', name: 'Copy Exceed Numbers', description: 'Copy numbers exceeding bet limits to clipboard as CSV format' },
    ],
  },
  {
    groupId: 'buy',
    groupName: 'Buy / Excess Offload',
    description: 'Offload high-risk excess numbers and manage external buy vouchers',
    permissions: [
      { key: 'buy.view', name: 'View Buy Workspace', description: 'Access the Buy / Excess Offload entry page and history' },
      { key: 'buy.create', name: 'Create Buy Voucher', description: 'Generate buy offload voucher to reduce risk liability' },
      { key: 'buy.update', name: 'Update Buy Voucher', description: 'Edit items and amounts in existing buy offload slips' },
      { key: 'buy.delete', name: 'Delete Buy Voucher', description: 'Delete a buy voucher and revert offloaded quantities' },
    ],
  },
  {
    groupId: 'history',
    groupName: 'Ledger Voucher History',
    description: 'Browse, search, export, and inspect saved session vouchers',
    permissions: [
      { key: 'history.view', name: 'View Voucher History', description: 'Open history modal and list all saved slips in the current session' },
      { key: 'history.view_details', name: 'View Voucher Details', description: 'Expand a voucher to view individual numbers, tokens, and subtotals' },
      { key: 'history.export_csv', name: 'Export History CSV', description: 'Download all history voucher slips as a CSV file' },
      { key: 'history.share', name: 'Share / Copy Slips Message', description: 'Copy formatted voucher text to clipboard or native share sheet' },
    ],
  },
  {
    groupId: 'agents',
    groupName: 'Agent Management',
    description: 'Manage agent profiles, contact information, commissions, and payout rates',
    permissions: [
      { key: 'agents.view', name: 'View Agents', description: 'View the list of agents, commission rates, and contact info' },
      { key: 'agents.create', name: 'Create Agent', description: 'Register a new agent profile with base commission % and payout rate' },
      { key: 'agents.edit', name: 'Edit Agent', description: 'Update agent profile, phone, address, and default rates' },
      { key: 'agents.delete', name: 'Delete Agent', description: 'Delete an agent profile' },
      { key: 'agents.copy_previous', name: 'Copy Previous Session Rates', description: 'Bulk-copy commission and rate settings from previous session' },
    ],
  },
  {
    groupId: 'session',
    groupName: 'Session Management',
    description: 'Control lottery time slots (09:30 AM, 12:00 PM, 04:30 PM), dates, and machines',
    permissions: [
      { key: 'session.view', name: 'View Active Session', description: 'View active session info (date, time slot, machine number)' },
      { key: 'session.change', name: 'Change / Pick Session', description: 'Switch active lottery session or open a new session slot' },
    ],
  },
  {
    groupId: 'reports',
    groupName: 'Reports & Financial Settlements',
    description: 'Inspect period settlements, sales totals, agent breakdowns, and commission matrices',
    permissions: [
      { key: 'reports.view', name: 'View Reports', description: 'Access Period Reports, Matrix summaries, and slip logs' },
      { key: 'reports.view_sales', name: 'View Quick Sales Reports', description: 'Open direct shortcuts for Sale 1 (By Agent) and Sale 2 (Summary)' },
      { key: 'reports.export_csv', name: 'Export Report CSV', description: 'Download settlement report in CSV spreadsheet format' },
      { key: 'reports.export_pdf', name: 'Export Report PDF', description: 'Generate and download formatted PDF settlement document' },
      { key: 'reports.commission_matrix.view', name: 'View Commission Matrix', description: 'Open weekly Monday–Friday agent commission grid editor' },
      { key: 'reports.commission_matrix.edit', name: 'Edit Commission Matrix', description: 'Override per-session commission rates for specific dates/slots' },
    ],
  },
  {
    groupId: 'balance',
    groupName: 'Balance & Payment Collection',
    description: 'Track agent debts, record received cash payments, and view net balance',
    permissions: [
      { key: 'balance.view', name: 'View Balances', description: 'Inspect balance due, payments received, and net balances by agent' },
      { key: 'balance.record', name: 'Record Payment', description: 'Record cash receipts received from agents' },
    ],
  },
  {
    groupId: 'settings',
    groupName: 'Organization Settings',
    description: 'Manage default payout rates, blocked numbers, hot numbers, and operating modes',
    permissions: [
      { key: 'settings.view', name: 'View Settings', description: 'View global payout rates, limits, blocked numbers, and local DB tools' },
      { key: 'settings.rates.update', name: 'Update Payout Rates', description: 'Update default payout multipliers (e.g. 80x)' },
      { key: 'settings.limit.update', name: 'Update Bet Limit', description: 'Set global default betting limit per number' },
      { key: 'settings.hot_numbers.manage', name: 'Manage Hot Numbers', description: 'Add or delete highlighted hot numbers for the session' },
      { key: 'settings.blocked_numbers.manage', name: 'Manage Blocked Numbers', description: 'Add or delete blocked/not-buy numbers' },
      { key: 'settings.operating_mode', name: 'Toggle Operating Mode', description: 'Switch between Cloud-First and Fully Offline standalone mode' },
      { key: 'settings.clean_data', name: 'Clean Local Storage Data', description: 'Purge old synced voucher cache before a specified date' },
    ],
  },
  {
    groupId: 'local_vouchers',
    groupName: 'Offline Queue & Local Vouchers',
    description: 'Monitor background synchronization, retry failed requests, and view cache',
    permissions: [
      { key: 'local_vouchers.view', name: 'View Local Vouchers', description: 'Inspect sync queue (Pending, Syncing, Failed, Synced)' },
      { key: 'local_vouchers.retry', name: 'Retry Sync', description: 'Re-trigger sync for single or all failed/pending offline vouchers' },
      { key: 'local_vouchers.clear_synced', name: 'Clear Synced Vouchers', description: 'Prune synced vouchers from browser storage' },
    ],
  },
  {
    groupId: 'admin',
    groupName: 'Organization Administration',
    description: 'Manage user accounts, roles, password requests, and audit logs',
    permissions: [
      { key: 'admin.users.view', name: 'View Users', description: 'View all member accounts and role assignments in the organization' },
      { key: 'admin.users.create', name: 'Create Member User', description: 'Create new supervisor or cashier accounts' },
      { key: 'admin.users.suspend', name: 'Suspend / Unsuspend User', description: 'Temporarily disable user access to the organization' },
      { key: 'admin.users.reset_password', name: 'Reset User Password', description: 'Generate a temporary login password for a staff member' },
      { key: 'admin.users.delete', name: 'Remove User', description: 'Delete a user account from the organization' },
      { key: 'admin.roles.manage', name: 'Manage Roles & Permissions', description: 'Create and configure custom user roles and permissions' },
      { key: 'admin.pw_requests.manage', name: 'Approve / Deny Password Requests', description: 'Manage forgot password requests submitted by staff' },
      { key: 'admin.logs.view', name: 'View Audit Activity Logs', description: 'Inspect audit trails of user logins, voucher edits, and role changes' },
    ],
  },
];

export const ALL_PERMISSION_KEYS = PERMISSION_GROUPS.flatMap((g) =>
  g.permissions.map((p) => p.key)
);

export const DEFAULT_ROLES = [
  {
    id: 'cashier',
    name: 'Cashier',
    description: 'Standard betting counter cashier with entry, local voucher, and basic history capabilities',
    isSystem: true,
    permissions: [
      'ledger.view',
      'ledger.create',
      'ledger.quick_entry',
      'ledger.import',
      'ledger.manage_tokens',
      'history.view',
      'history.view_details',
      'history.export_csv',
      'history.share',
      'agents.view',
      'session.view',
      'local_vouchers.view',
      'local_vouchers.retry',
    ],
  },
  {
    id: 'supervisor',
    name: 'Supervisor',
    description: 'Floor supervisor with editing rights, settlements, buy offload, reports, and agent setup',
    isSystem: true,
    permissions: [
      'ledger.view',
      'ledger.create',
      'ledger.update',
      'ledger.delete',
      'ledger.quick_entry',
      'ledger.import',
      'ledger.manage_tokens',
      'ledger.set_lucky',
      'ledger.set_limit',
      'ledger.check_agent',
      'ledger.export_grid',
      'ledger.copy_exceed',
      'buy.view',
      'buy.create',
      'buy.update',
      'buy.delete',
      'history.view',
      'history.view_details',
      'history.export_csv',
      'history.share',
      'agents.view',
      'agents.create',
      'agents.edit',
      'agents.copy_previous',
      'session.view',
      'session.change',
      'reports.view',
      'reports.view_sales',
      'reports.export_csv',
      'reports.export_pdf',
      'reports.commission_matrix.view',
      'reports.commission_matrix.edit',
      'balance.view',
      'balance.record',
      'settings.view',
      'settings.hot_numbers.manage',
      'settings.blocked_numbers.manage',
      'local_vouchers.view',
      'local_vouchers.retry',
      'local_vouchers.clear_synced',
    ],
  },
  {
    id: 'org_admin',
    name: 'Organization Admin',
    description: 'Full access to organization configuration, members, and all operational modules',
    isSystem: true,
    permissions: ALL_PERMISSION_KEYS,
  },
];
